version: "3"

services:
  power_prophet_redis:
    container_name: power_prophet_redis
    image: redis:7.2.4-bookworm
    restart: always
    networks:
      - power_prophet_backend_network

  power_prophet_backend_db:
    container_name: power_prophet_backend_db
    image: postgres:16
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - power_prophet_backend_pgdata:/var/lib/postgresql/data/
    env_file:
      - .dockerenv
    ports:
      - "5434:5432"
    networks:
      - power_prophet_backend_network

  power_prophet_backend_app:
    container_name: power_prophet_backend_app
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - .:/app
    depends_on:
      - power_prophet_backend_db
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/docs"]
      interval: 5s
      timeout: 10s
      retries: 50
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - power_prophet_backend_network

  power_prophet_worker:
    container_name: power_prophet_backend_worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
    environment:
      TZ: Asia/Shanghai
    depends_on:
      power_prophet_redis:
        condition: service_started
      power_prophet_backend_app:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - power_prophet_backend_network

  power_prophet_beat:
    container_name: power_prophet_backend_beat
    build:
      context: .
      dockerfile: Dockerfile.beat
    restart: always
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - power_prophet_worker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - power_prophet_backend_network

  power_prophet_flower:
    container_name: power_prophet_backend_flower
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.flower
    environment:
      TZ: Asia/Shanghai
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555"]
      interval: 5s
      timeout: 10s
      retries: 50
    ports:
      - 5555:5555
    depends_on:
      - power_prophet_worker
    networks:
      - power_prophet_backend_network

volumes:
  power_prophet_backend_pgdata:
    driver: local

networks:
  power_prophet_backend_network:
    driver: bridge
