version: "3.7"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
